/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UnilogRouteImport } from './routes/unilog'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as ProductsIdEvidenceRouteImport } from './routes/products_.$id.evidence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UnilogRoute = UnilogRouteImport.update({
  id: '/unilog',
  path: '/unilog',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdEvidenceRoute = ProductsIdEvidenceRouteImport.update({
  id: '/products_/$id/evidence',
  path: '/products/$id/evidence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/unilog': typeof UnilogRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/new': typeof ProductsNewRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$id/evidence': typeof ProductsIdEvidenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/unilog': typeof UnilogRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/new': typeof ProductsNewRoute
  '/products': typeof ProductsIndexRoute
  '/products/$id/evidence': typeof ProductsIdEvidenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/unilog': typeof UnilogRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/new': typeof ProductsNewRoute
  '/products/': typeof ProductsIndexRoute
  '/products_/$id/evidence': typeof ProductsIdEvidenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/dashboard'
    | '/reviews'
    | '/settings'
    | '/unilog'
    | '/products/$id'
    | '/products/new'
    | '/products/'
    | '/products/$id/evidence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/dashboard'
    | '/reviews'
    | '/settings'
    | '/unilog'
    | '/products/$id'
    | '/products/new'
    | '/products'
    | '/products/$id/evidence'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/dashboard'
    | '/reviews'
    | '/settings'
    | '/unilog'
    | '/products/$id'
    | '/products/new'
    | '/products/'
    | '/products_/$id/evidence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  DashboardRoute: typeof DashboardRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
  UnilogRoute: typeof UnilogRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsIdEvidenceRoute: typeof ProductsIdEvidenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unilog': {
      id: '/unilog'
      path: '/unilog'
      fullPath: '/unilog'
      preLoaderRoute: typeof UnilogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$id/evidence': {
      id: '/products_/$id/evidence'
      path: '/products/$id/evidence'
      fullPath: '/products/$id/evidence'
      preLoaderRoute: typeof ProductsIdEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  DashboardRoute: DashboardRoute,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
  UnilogRoute: UnilogRoute,
  ProductsIdRoute: ProductsIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsIdEvidenceRoute: ProductsIdEvidenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
